# Generated by Django 5.2.6 on 2025-09-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_master', models.CharField(max_length=32)),
                ('mac_slave', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='C', max_length=8)),
                ('ts', models.BigIntegerField()),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('firmware', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
